### PR TITLE
ignore root variables

### PR DESCRIPTION
**Pull request by rubyu**
### repro

Adding the following line in the target project:
```go
var testString = `test string`
```

### expected

Nothing to be output relating to string

### got

```
	gouml.modelKind ..> string : <<use>> 
	gouml.modelKind ..> string : <<use>> 
	gouml.modelKind ..> string : <<return>> 
```

### details

I had encountered an issue that all `return` and `use` of `string` are  shown in UML, the picture rendered  is the following:
スクリーンショット 2019-04-17 12 54 47

Adding a check whether the type of object is `*types:Var` or not in exploring it may fix this problem,  I guess. But I haven't enough confidence. I would be glad if you give me an advice.

### CODE REVIEW

**Comment by kazukousen** [comment]
@rubyu thanks, this looks pretty good.
but, sorry, I discovered this bug and patched to master branch already. #20 
please give update this library and retry parsing. 
Thanks

**Comment by kazukousen** [comment]
oops, not resolved yet...?

**Comment by rubyu** [comment]
Thank you for your quick reply. I had `go get -u` again, and everything is going well now!
And lastly, let me say thank you again. I think this tool will be very important thing to all the people who write golang. Cheers!🍻

**Comment by kazukousen** [comment]
I'm glad to hear that!
Thank you.

**Pull request closed without merging**
